steps:

- id: install
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: lint
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','lint']

- id: build
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','build']
  env:
    - 'NODE_ENV=production'
    - 'VUE_APP_GOOGLE_ANALYTICS_ID=$_VUE_APP_GOOGLE_ANALYTICS_ID'
    - 'VUE_APP_GOOGLE_ANALYTICS_DEBUG=false'
    - 'VUE_APP_HOST=$_VUE_APP_HOST'

- id: deploy
  name: 'gcr.io/kellyferrone/firebase'
  args: ['deploy','--only','hosting']
  env:
    - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'

substitutions:
  _FIREBASE_TOKEN: token
  _VUE_APP_GOOGLE_ANALYTICS_ID: ua
  _VUE_APP_HOST: https://example.com
