steps:

- id: install
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: lint
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','lint']

- id: build
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','build']
  env:
    - 'NODE_ENV=production'
    - 'VUE_APP_BLOGGER_API_KEY=$_VUE_APP_BLOGGER_API_KEY'
    - 'VUE_APP_BLOGGER_BLOG_ID=$_VUE_APP_BLOGGER_BLOG_ID'
    - 'VUE_APP_GOOGLE_ANALYTICS=$_VUE_APP_GOOGLE_ANALYTICS'
    
- id: deploy
  name: 'gcr.io/kellyferrone-211016/firebase'
  args: ['deploy','--only','hosting']
  env:
    - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'

substitutions:
  _FIREBASE_TOKEN: token
  _VUE_APP_BLOGGER_API_KEY: key
  _VUE_APP_BLOGGER_BLOG_ID: id
  _VUE_APP_GOOGLE_ANALYTICS: ua